org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1
mod_id=pm_equips
mod_authors=Rei
mod_name=ProjectMoon Equipments Mod
mod_license=MIT
mod_version=3.2
mod_group_id=pm_equips
mod_description=Credit by ProjectMoon.

mixin.genPaperwork=true