modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "pm_equips"
version = "5.0"
displayName = "ProjectMoon Equipment Mod"
authors = "Rei"
description = "Face the fear, Make the future."

[[dependencies."pm_equips"]]
modId = "forge"
mandatory = true
versionRange = "47.4.10"
ordering = "NONE"
side = "BOTH"

[[dependencies."pm_equips"]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "NONE"
side = "BOTH"

[[dependencies."pm_equips"]]
modId="geckolib"
mandatory=true
versionRange="[4.7.4,)"
ordering="AFTER"
side="BOTH"

[[dependencies."pm_equips"]]
modId="curios"
mandatory=true
versionRange="[5.14.1,)"
ordering="AFTER"
side="BOTH"
requiredMods = ["curios"]

[[mixins]]
config="pm_equips.mixins.json"

[[dependencies."pm_equips"]]
modId="jei"
mandatory=false
versionRange="[15,)"
ordering="NONE"
side="BOTH"