package net.pm_equips.tabs;

import net.minecraft.world.item.Item;
import net.pm_equips.ItemInit;

public class PMWingsTabs {
    public static final Item[] items = {
            ItemInit.WCORP_WEAPON_1.get(),
            ItemInit.WCORP_WEAPON_2.get(),
            ItemInit.WCORP_WEAPON_3.get(),
            ItemInit.WCORP_ARMOR_L1.get(),
            ItemInit.WCORP_ARMOR_L2.get(),
            ItemInit.WCORP_ARMOR_L3.get(),
            ItemInit.WCORP_ARMOR_L4.get(),
            ItemInit.WCORP_ARMOR_L5.get(),
            ItemInit.RCORP_RABBIT_KNIFE.get(),
            ItemInit.RCORP_RABBIT_RIFLE.get(),
            ItemInit.RCORP_RABBIT_ARMOR_L1.get(),
            ItemInit.RCORP_RABBIT_ARMOR_L2.get(),
            ItemInit.RCORP_RABBIT_ARMOR_L3.get(),
            ItemInit.RCORP_RABBIT_ARMOR_L4.get(),
            ItemInit.RCORP_RABBIT_ARMOR_L5.get(),
            ItemInit.KCORP_WEAPON_1.get(),
            ItemInit.KCORP_WEAPON_2.get(),
            ItemInit.KCORP_WEAPON_3.get(),
            ItemInit.KCORP_OFFICER_ARMOR_L1.get(),
            ItemInit.KCORP_OFFICER_ARMOR_L2.get(),
            ItemInit.KCORP_AGENT_ARMOR_L3.get(),
            ItemInit.KCORP_AGENT_ARMOR_L4.get(),
            ItemInit.KCORP_AGENT_ARMOR_L5.get(),
            ItemInit.HCORP_MAO_WEAPON.get(),
            ItemInit.HCORP_MAO_ARMOR_L1.get(),
            ItemInit.HCORP_MAO_ARMOR_L2.get(),
            ItemInit.HCORP_MAO_ARMOR_L3.get(),
            ItemInit.HCORP_MAO_ARMOR_L4.get(),
            ItemInit.HCORP_MAO_ARMOR_L5.get(),
            ItemInit.HCORP_SI_WEAPON.get(),
            ItemInit.HCORP_SI_ARMOR_L1.get(),
            ItemInit.HCORP_SI_ARMOR_L2.get(),
            ItemInit.HCORP_SI_ARMOR_L3.get(),
            ItemInit.HCORP_SI_ARMOR_L4.get(),
            ItemInit.HCORP_SI_ARMOR_L5.get(),
            ItemInit.HCORP_YOU_WEAPON.get(),
            ItemInit.HCORP_YOU_ARMOR_L1.get(),
            ItemInit.HCORP_YOU_ARMOR_L2.get(),
            ItemInit.HCORP_YOU_ARMOR_L3.get(),
            ItemInit.HCORP_YOU_ARMOR_L4.get(),
            ItemInit.HCORP_YOU_ARMOR_L5.get(),
            ItemInit.HEAD_CLAW.get(),
    };
}
